[package]
name = "stsync-gst"
version = "0.1.0"
edition = "2021"
description = "Highter level gstreamer bindings"

[dependencies]
futures = "0.3.25"
gstreamer = "0.18.8"
gstreamer-app = "0.18.7"
tracing = "0.1.37"
